### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/printnanny-sdwire#3]
### Pre-orders open
- [x] Upgrade Ghost blog to 5.x (support for comments)
- [x] Publish blog post - CTA pre-order now, CTA Ask the Electrical Engineer (comments)
- [x] Launch email 1 - announce pre-orders open + Ask the Electrical Engineer
- [x] Twitter
- [x] Discord
- [ ] Show HackerNews post, w/ Ask the Electrical Engineer
- [ ] Launch email 2 - a roundup of Ask the Electrical Engineer

### Batch 1
- [ ] Assembly + QA, see #1 
- [x] Photos
- [ ] Ship + Notify
- [ ] Publish a blog post about QA + fulfillment process, earnings, learnings
- [ ] Launch email 3 - a roundup of earnings, learnings
- [ ] Twitter
- [ ] Discord
- [ ] Show HackerNews post, w/ Ask the Electrical Engineer
